### ISSUE TITLE
We are now tracking git.blender.org

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#73]
@Eibriel @fsiddi @Alexey-Akishin @brechtvl : 

I updated the repository replacing <b>master</b> and <b>multiview</b>. That means any fork/branch will have to be re-created:
- Master is a 1:1 copy of git.blender.org.
- Multiview is a transplanted version of the old branch, but updated with master.
- <b>old-master</b> and <b>old-multiview</b> are backups.
- Master and multiview are one level in (no more //blender/ folder)

Also, I updated the building instructions, feel free to add any fix there, I didn't test it from scratch.

Finally, if you really need to transplant any branch non-manually from the old master this script may help: https://gist.github.com/dfelinto/7558432

**Comment by Alexey-Akishin** [comment]
It's good news. But I encountered an error when trying to download the repository:

Cloning into 'release/datafiles/locale'...
Username for 'https://github.com': Alexey-Akishin
Password for 'https://Alexey-Akishin@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/dfelinto/blender-translations.git/' not found
Clone of 'https://github.com/dfelinto/blender-translations.git' into submodule path 'release/datafiles/locale' failed

Similar error happens when trying to update. I do not think it should ask for login/password when updating locale submodule, and even if I enter them correctly, update of this submodule fails anyway. This is of course just minor annoyance because Blender can be build without locale, but I thought I mention it.

**Comment by EibrielInv** [comment]
Hi @Alexey-Akishin , before

```
git submodule update --init --recursive --remote
```

You need to:

```
git config submodule.scons.url git://git.blender.org/scons.git
git config submodule.release/scripts/addons_contrib.url git://git.blender.org/blender-addons-contrib.git
git config submodule.release/scripts/addons.url git://git.blender.org/blender-addons.git
git config submodule.release/datafiles/locale.url git://git.blender.org/blender-translations.git
```

**Comment by Alexey-Akishin** [comment]
@Eibriel , thanks, now everything works as expected.

**Comment by dfelinto** [comment]
all good, I just updated the building instructions. If there is anything missing, please pull request ;)
closing the issue now
